# Generated by Django 5.0.4 on 2024-04-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evenement',
            table='evenements',
        ),
    ]
