# Generated by Django 5.0.4 on 2024-04-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resApp', '0002_alter_evenement_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='lieu',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='titre',
        ),
        migrations.AddField(
            model_name='evenement',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
