# Generated by Django 5.0.4 on 2024-04-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resApp', '0003_remove_evenement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='created_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='created_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='created_by_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
