# Generated by Django 5.0.4 on 2024-04-11 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resApp', '0004_evenement_created_by_email_evenement_created_by_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='created_by_email',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='created_by_id',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='created_by_username',
        ),
        migrations.AddField(
            model_name='evenement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
